In [21]:
%load_ext autoreload
%autoreload 2

In [17]:
import pandas as pd
import os
import warnings
# Suppress SSL and general warnings
warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", message="Unverified HTTPS request")

In [12]:
companies_df = pd.read_csv("./private_data/companies.csv")[["name", "location", "domain", "id", "tagline"]]
enriched_df = pd.read_csv("./private_data/enriched_companies.csv")
for index, row in enriched_df.iterrows():
    location = row["Location"]
    if pd.isna(location):
        id = row["id"]
        company = companies_df[companies_df["id"] == id]
        location = company["location"].values[0]
        enriched_df.at[index, "Location"] = location

enriched_df.to_csv("./private_data/enriched_companies.csv", index=False)

In [15]:
funding_rounds = pd.read_csv("./private_data/funding_rounds.csv")
funding_ids = sorted(funding_rounds["company_id"].unique().tolist())
enriched_ids = sorted(enriched_df["id"].unique().tolist())

In [11]:
import imaplib
import email
from email.header import decode_header
from bs4 import BeautifulSoup
from config import EMAIL_ADDRESS, EMAIL_PASSWORD, IMAP_SERVER, WATCHLIST
from uid_tracker import is_uid_seen, mark_uid_seen
from parser import ctvc, ctvc_date 

def fetch_unread_newsletters():
    imap = imaplib.IMAP4_SSL(IMAP_SERVER)
    imap.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
    imap.select("Inbox")

    messages = []

    for sender in WATCHLIST:
        sender = sender.strip()
    
        status, response = imap.search(None, f'FROM "{sender}"')
        if status != "OK":
            print(f"❌ Failed to search inbox for {sender}")
            continue

        email_ids = response[0].split()
        for eid in reversed(email_ids):  # latest first
            uid = eid.decode()
            # if is_uid_seen(sender, uid):
            #     continue

            status, msg_data = imap.fetch(eid, "(RFC822)")
            if status != "OK":
                continue
            raw_email = msg_data[0][1]
            msg = email.message_from_bytes(raw_email)
            html_content = None
            if msg.is_multipart():
                for part in msg.walk():
                    if part.get_content_type() == "text/html":
                        html_content = part.get_payload(decode=True).decode("utf-8", errors="ignore")
                        break
            else:
                html_content = msg.get_payload(decode=True).decode("utf-8", errors="ignore")

            if html_content:
                messages.append({
                    "sender": sender,
                    "uid": uid,
                    "html": html_content,
                    "subject": msg["Subject"]
                })
                # mark_uid_seen(sender, uid)

    imap.logout()
    return messages


import imaplib
import email
from email.header import decode_header
from bs4 import BeautifulSoup
from config import EMAIL_ADDRESS, EMAIL_PASSWORD, IMAP_SERVER, WATCHLIST
from uid_tracker import is_uid_seen, mark_uid_seen


def fetch_unread_newsletters():
    imap = imaplib.IMAP4_SSL(IMAP_SERVER)
    imap.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
    imap.select("Inbox")

    messages = []

    for sender in WATCHLIST:
        sender = sender.strip()
        status, response = imap.search(None, f'FROM "{sender}"')
        if status != "OK":
            print(f"❌ Failed to search inbox for {sender}")
            continue

        email_ids = response[0].split()
        for eid in reversed(email_ids):  # latest first
            uid = eid.decode()
            # if is_uid_seen(sender, uid):
            #     continue

            status, msg_data = imap.fetch(eid, "(RFC822)")
            if status != "OK":
                continue

            raw_email = msg_data[0][1]
            msg = email.message_from_bytes(raw_email)

            html_content = None
            text_content = None
            if msg.is_multipart():
                for part in msg.walk():
                    content_type = part.get_content_type()
                    # print(f"THIS IS THE CONTENT TYPE {content_type}")
                    if content_type == "text/html":
                        html_content = part.get_payload(decode=True).decode("utf-8", errors="ignore")
                    elif content_type == "text/plain":
                        text_content = part.get_payload(decode=True).decode("utf-8", errors="ignore")
            else:
                content_type = msg.get_content_type()
                # print(f"THIS IS THE CONTENT TYPE {content_type}")

                if content_type == "text/html":
                    html_content = msg.get_payload(decode=True).decode("utf-8", errors="ignore")
                elif content_type == "text/plain":
                    text_content = msg.get_payload(decode=True).decode("utf-8", errors="ignore")

            if html_content or text_content:
                messages.append({
                    "sender": sender,
                    "uid": uid,
                    "html": html_content,
                    "text": text_content,
                    "subject": msg["Subject"]
                })
                # mark_uid_seen(sender, uid)

    imap.logout()
    return messages

print(f"{WATCHLIST=}")
result = fetch_unread_newsletters()
sender = result[0]["sender"]
# sender_function_map = {"hello@ctvc.co",:None,"newsletter@keepcool.co":None}
html = (result[0]["html"])

# ctvc(html)

WATCHLIST=['hello@ctvc.co', 'newsletter@keepcool.co', 'climatetech@dealflowweekly.com']

In [16]:
from datetime import datetime
def ctvc_date(html: str) -> datetime.date:
    """
    Extracts the publication date from a CTVC newsletter URL and returns it as a date object (YYYY-MM-DD).
    """
    try:
        # response = requests.get(url, verify=False, timeout=5)
        # response.raise_for_status()
        soup = BeautifulSoup(html, "html.parser")
        date_element = soup.find('span', class_='post-meta-date')

        if date_element:
            date_text = date_element.get_text(strip=True)
        return datetime.strptime(date_text, "%d %b %Y")

        # date_tag = soup.find("time")
        # if date_tag and 'datetime' in date_tag.attrs:
        #     date_str = date_tag['datetime']
        #     return datetime.fromisoformat(date_str.replace("Z", "+00:00")).date()
        # else:
        #     raise ValueError("No <time> tag with datetime attribute found.")
    except Exception as e:
        raise RuntimeError(f"Failed to fetch or parse date: {e}")
    

html

'<!doctype html>\r\n<html>\r\n    <head>\r\n        <meta name="viewport" content="width=device-width">\r\n        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\r\n        <!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]-->\r\n        <title>&#x1F30E; Taxing times for CCUS #254</title>\r\n        <style>\r\n.post-title-link {\r\n  display: block;\r\n  margin-top: 32px;\r\n  color: #15212A;\r\n  text-align: center;\r\n  line-height: 1.1em;\r\n}\r\n.post-title-link-left {\r\n  text-align: left;\r\n}\r\n.view-online-link {\r\n  word-wrap: none;\r\n  white-space: nowrap;\r\n  color: #15212a;\r\n  color: rgba(0, 0, 0, 0.6);\r\n  text-decoration: underline !important;\r\n}\r\n.kg-nft-link {\r\n  display: block;\r\n  text-decoration: none !important;\r\n  color: #15212A !important;\r\n  font-family: inherit !important;\r\n  font-size: 14px;\r\n  line-height: 1.3em;\r\n  padding-top: 4px;\r\n  padding-right: 20px;\r\n  padding-left: 20px;\r\n  padding-bottom: 4px;\r\n}\r\n.kg-twitter-link {\r\n  display: block;\r\n  text-decoration: none !important;\r\n  color: #15212A !important;\r\n  font-family: inherit !important;\r\n  font-size: 15px;\r\n  padding: 8px;\r\n  line-height: 1.3em;\r\n}\r\n.kg-cta-link-accent .kg-cta-sponsor-label a {\r\n  color: #03989e !important;\r\n}\r\n.kg-cta-text a:not(.kg-cta-link-accent .kg-cta-text a) {\r\n  color: #15212A;\r\n  text-decoration: underline;\r\n}\r\n.kg-cta-link-accent .kg-cta-text a {\r\n  color: #03989e !important;\r\n}\r\n.kg-audio-link {\r\n  color: #15212a !important;\r\n  color: rgba(0, 0, 0, 0.6) !important;\r\n}\r\n@media only screen and (max-width: 620px) {\r\n  table.body {\r\n    width: 100%;\r\n    min-width: 100%;\r\n  }\r\n\r\n  .hide-mobile {\r\n    display: none;\r\n  }\r\n\r\n  .mobile-only {\r\n    display: initial !important;\r\n  }\r\n\r\n  .hide-desktop {\r\n    display: initial !important;\r\n  }\r\n\r\n  .desktop-only {\r\n    display: none !important;\r\n  }\r\n\r\n  table.body p,\r\ntable.body ul,\r\ntable.body ol,\r\ntable.body td {\r\n    font-size: 16px;\r\n  }\r\n\r\n  table.header .post-excerpt {\r\n    font-size: 16px !important;\r\n  }\r\n\r\n  table.body .kg-callout-card {\r\n    padding: 16px 24px !important;\r\n  }\r\n\r\n  table.body .kg-callout-text {\r\n    font-size: 16px !important;\r\n    line-height: 1.5em !important;\r\n  }\r\n\r\n  table.body pre {\r\n    white-space: pre-wrap !important;\r\n    word-break: break-word !important;\r\n  }\r\n\r\n  table.body .content {\r\n    padding: 0 !important;\r\n  }\r\n\r\n  table.body .container {\r\n    padding: 0 !important;\r\n    width: 100% !important;\r\n  }\r\n\r\n  table.body .main,\r\ntable.header .header-main {\r\n    border-spacing: 10px 0 !important;\r\n    border-left-width: 0 !important;\r\n    border-radius: 0 !important;\r\n    border-right-width: 0 !important;\r\n  }\r\n\r\n  table.body .img-responsive {\r\n    height: auto !important;\r\n    max-width: 100% !important;\r\n    width: auto !important;\r\n  }\r\n\r\n  table.header .site-icon {\r\n    padding-top: 0 !important;\r\n  }\r\n\r\n  table.header .site-info {\r\n    padding-top: 24px !important;\r\n  }\r\n\r\n  table.header .post-title-link {\r\n    margin-top: 24px !important;\r\n  }\r\n\r\n  table.header .post-meta-wrapper {\r\n    padding-bottom: 24px !important;\r\n  }\r\n\r\n  table.header .site-icon img {\r\n    width: 36px !important;\r\n    height: 36px !important;\r\n  }\r\n\r\n  table.header .site-url a {\r\n    font-size: 13px !important;\r\n    padding-bottom: 16px !important;\r\n  }\r\n\r\n  table.header .post-meta,\r\ntable.header .post-meta-date {\r\n    white-space: normal !important;\r\n    font-size: 13px !important;\r\n    line-height: 1.2em;\r\n  }\r\n\r\n  table.header .post-meta,\r\ntable.header .view-online {\r\n    width: 100% !important;\r\n  }\r\n\r\n  table.header .post-meta-left,\r\ntable.header .post-meta-left.view-online {\r\n    width: 100% !important;\r\n    text-align: left !important;\r\n  }\r\n\r\n  table.header .post-meta.view-online-mobile {\r\n    display: table-row !important;\r\n  }\r\n\r\n  table.header .post-meta-left.view-online-mobile,\r\ntable.header .post-meta-left.view-online-mobile .view-online {\r\n    text-align: left !important;\r\n  }\r\n\r\n  table.header .post-meta.view-online.desktop {\r\n    display: none !important;\r\n  }\r\n\r\n  table.header .view-online {\r\n    text-decoration: underline;\r\n  }\r\n\r\n  table.body .footer p,\r\ntable.body .footer p span {\r\n    font-size: 13px !important;\r\n  }\r\n\r\n  table.header .view-online-link,\r\ntable.body .footer,\r\ntable.body .footer a {\r\n    font-size: 13px !important;\r\n  }\r\n\r\n  table.header .post-title a {\r\n    font-size: 26px !important;\r\n    line-height: 1.1em !important;\r\n  }\r\n\r\n  table.feedback-buttons {\r\n    display: table !important;\r\n    width: 100% !important;\r\n    max-width: 390px;\r\n  }\r\n\r\n  table.feedback-buttons img {\r\n    display: inherit !important;\r\n  }\r\n\r\n  table.body .feedback-button-text {\r\n    display: none!important;\r\n  }\r\n\r\n  table.body .latest-posts-header {\r\n    font-size: 12px !important;\r\n  }\r\n\r\n  table.body .latest-post-title {\r\n    padding-right: 8px !important;\r\n  }\r\n\r\n  table.body .latest-post h4,\r\ntable.body .latest-post h4 span {\r\n    padding: 4px 0 6px !important;\r\n    font-size: 15px !important;\r\n  }\r\n\r\n  table.body .latest-post-excerpt,\r\ntable.body .latest-post-excerpt a,\r\ntable.body .latest-post-excerpt span {\r\n    font-size: 13px !important;\r\n    line-height: 1.2 !important;\r\n  }\r\n\r\n  table.body .subscription-box h3 {\r\n    font-size: 14px !important;\r\n  }\r\n\r\n  table.body .subscription-box p,\r\ntable.body .subscription-box p span {\r\n    font-size: 13px !important;\r\n  }\r\n\r\n  table.body .subscription-details,\r\ntable.body .manage-subscription {\r\n    display: inline-block;\r\n    width: 100%;\r\n    text-align: left !important;\r\n    font-size: 13px !important;\r\n  }\r\n\r\n  table.body .subscription-details {\r\n    padding-bottom: 12px;\r\n  }\r\n\r\n  table.body .kg-bookmark-card {\r\n    width: 90vw;\r\n  }\r\n\r\n  table.body .kg-bookmark-thumbnail {\r\n    display: none !important;\r\n  }\r\n\r\n  table.body .kg-bookmark-metadata span {\r\n    font-size: 13px !important;\r\n  }\r\n\r\n  table.body .kg-embed-card {\r\n    max-width: 90vw !important;\r\n  }\r\n\r\n  table.body h1 {\r\n    font-size: 32px !important;\r\n    line-height: 1.3em !important;\r\n  }\r\n\r\n  table.body h2,\r\ntable.body h2 span {\r\n    font-size: 26px !important;\r\n    line-height: 1.22em !important;\r\n  }\r\n\r\n  table.body h3 {\r\n    font-size: 21px !important;\r\n    line-height: 1.25em !important;\r\n  }\r\n\r\n  table.body h4 {\r\n    font-size: 19px !important;\r\n    line-height: 1.3em !important;\r\n  }\r\n\r\n  table.body h5 {\r\n    font-size: 16px !important;\r\n    line-height: 1.4em !important;\r\n  }\r\n\r\n  table.body h6 {\r\n    font-size: 16px !important;\r\n    line-height: 1.4em !important;\r\n  }\r\n\r\n  table.body blockquote {\r\n    font-size: 16px !important;\r\n    line-height: 1.6em;\r\n    margin-bottom: 0;\r\n  }\r\n\r\n  table.body blockquote p {\r\n    margin-right: 15px !important;\r\n    margin-left: 15px !important;\r\n  }\r\n\r\n  table.body blockquote.kg-blockquote-alt {\r\n    border-left: 0 none !important;\r\n    margin: 0 !important;\r\n    font-size: 18px !important;\r\n    line-height: 1.4em !important;\r\n  }\r\n\r\n  table.body blockquote.kg-blockquote-alt p {\r\n    margin-right: 20px !important;\r\n    margin-left: 20px !important;\r\n  }\r\n\r\n  table.body hr {\r\n    margin: 2em 0 !important;\r\n  }\r\n\r\n  .feature-image-caption {\r\n    font-size: 13px!important;\r\n  }\r\n\r\n  .kg-card-figcaption {\r\n    font-size: 13px!important;\r\n  }\r\n\r\n  .kg-card-figcaption p,\r\n.kg-card-figcaption p span {\r\n    font-size: 13px!important;\r\n  }\r\n\r\n  table.body .kg-cta-card {\r\n    padding: 0 20px;\r\n  }\r\n\r\n  table.body .kg-cta-card.kg-cta-bg-none {\r\n    padding: 0;\r\n  }\r\n\r\n  table.body .kg-cta-sponsor-label {\r\n    padding: 10px 0;\r\n  }\r\n\r\n  table.body table.kg-cta-content-wrapper:not(.kg-cta-bg-none.kg-cta-no-dividers table.kg-cta-content-wrapper) {\r\n    padding: 20px 0;\r\n  }\r\n\r\n  table.body .kg-cta-immersive.kg-cta-has-img:not(.kg-cta-bg-none):not(.kg-cta-no-label) table.kg-cta-content-wrapper {\r\n    padding-top: 0;\r\n  }\r\n\r\n  table.body .kg-cta-minimal .kg-cta-image-container {\r\n    padding-right: 20px;\r\n  }\r\n\r\n  table.body .kg-cta-immersive .kg-cta-image-container {\r\n    padding-bottom: 20px;\r\n  }\r\n\r\n  table.body .kg-cta-immersive.kg-cta-no-text .kg-cta-image-container {\r\n    padding-bottom: 0;\r\n  }\r\n\r\n  table.body .kg-cta-button-container {\r\n    padding-top: 16px;\r\n  }\r\n\r\n  table.body .kg-cta-minimal .kg-cta-image-container {\r\n    display: inline-block !important;\r\n    width: 100% !important;\r\n    padding: 0 !important;\r\n    padding-bottom: 16px !important;\r\n    padding-right: 0 !important;\r\n  }\r\n\r\n  table.body .kg-cta-minimal .kg-cta-content-inner {\r\n    display: inline-block !important;\r\n    width: 100% !important;\r\n    padding: 0 !important;\r\n  }\r\n\r\n  table.body .kg-cta-minimal img.kg-cta-image {\r\n    width: 52px !important;\r\n    height: 52px !important;\r\n  }\r\n}\r\n@media all {\r\n  .subscription-details p.hidden {\r\n    display: none !important;\r\n  }\r\n\r\n  .ExternalClass {\r\n    width: 100%;\r\n  }\r\n\r\n  .ExternalClass,\r\n.ExternalClass p,\r\n.ExternalClass span,\r\n.ExternalClass font,\r\n.ExternalClass td,\r\n.ExternalClass div {\r\n    line-height: 100%;\r\n  }\r\n\r\n  .apple-link a {\r\n    color: inherit !important;\r\n    font-family: inherit !important;\r\n    font-size: inherit !important;\r\n    font-weight: inherit !important;\r\n    line-height: inherit !important;\r\n    text-decoration: none !important;\r\n  }\r\n\r\n  #MessageViewBody a {\r\n    color: inherit;\r\n    text-decoration: none;\r\n    font-size: inherit;\r\n    font-family: inherit;\r\n    font-weight: inherit;\r\n    line-height: inherit;\r\n  }\r\n}\r\n</style>\r\n    </head>\r\n    <body style="background-color: #fff; font-family: -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; font-size: 18px; line-height: 0; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: #15212A;"><img width="1" height="1" alt="" src="http://email.ghost.ctvc.co/o/eJw8zkGu6yAMheHVPGaJjMHYDLyYgEmKXhKkXtr1X7WDOzzS-aXP1IAagWvqmZAQckyuXVs_l26ahImkCbCktgOAt1BCDu6huwC2SHlD2BnAUuREMWw1owUu1XVFQAL20WdEpFUisfcliMRcLMO_CMdj_My1zndd63BP3V-39fuwtp3XuPscz8_po1nruNzU8jr_L1-em_qt_1Y5x7FIgsDRvRV_AwAA__93yj_W">\r\n        <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;">OBBB blows tailwinds through CCUS, but takeoff stalls</span>\r\n\r\n        <!-- HEADER WITH FULL-WIDTH BACKGROUND -->\r\n            <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="header" width="100%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; line-height: 1.4; background-color: #ffffff; width: 100%; border-spacing: 0; border-collapse: collapse;" bgcolor="#ffffff">\r\n                <!-- Outlook doesn\'t respect max-width so we need an extra centered table -->\r\n                <!--[if mso]>\r\n                <tr>\r\n                    <td>\r\n                        <center>\r\n                            <table border="0" cellpadding="0" cellspacing="0" width="600">\r\n                <![endif]-->\r\n                <tr>\r\n                    <td style="font-family: -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif; font-size: 18px; vertical-align: top; color: #15212A;" valign="top">&#xA0;</td>\r\n                    <td class="container" align="center" style="font-family: -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif; font-size: 18px; vertical-align: top; color: #15212A;" valign="top">\r\n                        <div class="content" style="box-sizing: border-box; display: block; margin: 0 auto; max-width: 600px;">\r\n                        <!-- Header content constrained to 600px -->\r\n                        <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="header-main" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 20px 0; width: 100%; max-width: 600px; background: #ffffff; background-color: transparent;" width="100%" bgcolor="transparent">\r\n                            <tr>\r\n                                <td class="header-content" style="font-family: -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif; font-size: 18px; vertical-align: top; color: #15212A; padding: 0; margin: 0 auto;" valign="top">\r\n                                    <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">\r\n\r\n                                            <tr class="site-info-row">\r\n                                                <td class="site-info" width="100%" align="center" style="font-family: -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif; font-size: 18px; vertical-align: top; color: #15212A; padding-top: 32px;" valign="top">\r\n                                                    <table role="presentation" border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">\r\n                                                            <tr>\r\n                                                                <td class="site-icon" style="font-family: -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif; font-size: 18px; vertical-align: top; color: #15212A; padding-bottom: 8px; padding-top: 8px; text-align: center; border-radius: 3px;" valign="top" align="center"><a href="https://www.ctvc.co/r/044b72bd?m=fa154ea2-883d-4569-a2d8-205feec38852" style="color: #03989e; text-decoration: none; overflow-wrap: anywhere;" target="_blank"><img src="https://www.ctvc.co/content/images/2022/07/favicon-ctvc-1.png" alt="CTVC by Sightline Climate" border="0" width="44" height="44" style="border: none; -ms-interpolation-mode: bicubic; max-width: 100%; width: 44px; height: 44px; border-radius: 3px;"></a></td>\r\n                                                            </tr>\r\n                                                            <tr>\r\n                                                                <td class="site-url site-url-bottom-padding" style="font-family: -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif; vertical-align: top; color: #15212A; font-size: 16px; letter-spacing: -0.1px; font-weight: 700; text-transform: uppercase; text-align: center; padding-bottom: 12px;" valign="top" align="center"><div style="width: 100% !important;"><a href="https://www.ctvc.co/r/0f5a3c5f?m=fa154ea2-883d-4569-a2d8-205feec38852" class="site-title" style="text-decoration: none; color: #15212A; overflow-wrap: anywhere;" target="_blank">CTVC by Sightline Climate</a></div></td>\r\n                                                            </tr>\r\n\r\n                                                    </table>\r\n                                                </td>\r\n                                            </tr>\r\n\r\n                                            <tr>\r\n                                                <td class="post-title post-title-with-excerpt" style="font-family: -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif; font-size: 18px; vertical-align: top; text-align: center; color: #000000; padding-bottom: 8px;" valign="top" align="center">\r\n                                                    <table role="presentation" border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">\r\n                                                        <tr>\r\n                                                            <td style="font-family: -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif; vertical-align: top; font-size: 36px; line-height: 1.1; font-weight: 700; text-align: center; color: #000000;" valign="top" align="center">\r\n                                                                <a href="https://www.ctvc.co/r/8d6c4c07?m=fa154ea2-883d-4569-a2d8-205feec38852" class="post-title-link" style="text-decoration: none; display: block; margin-top: 32px; text-align: center; line-height: 1.1em; overflow-wrap: anywhere; color: #000000;" target="_blank">&#x1F30E; Taxing times for CCUS #254</a>\r\n                                                            </td>\r\n                                                        </tr>\r\n                                                    </table>\r\n                                                </td>\r\n                                            </tr>\r\n                                            <tr>\r\n                                                <td width="100%" style="font-family: -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif; font-size: 18px; vertical-align: top; color: #15212A; width: 100%;" align="center" valign="top">\r\n                                                    <table class="post-meta-wrapper" role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; padding-bottom: 32px;">\r\n                                                        <tr>\r\n                                                            <td height="20" class="post-meta post-meta-center" style="font-family: -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif; vertical-align: top; color: #15212a; color: rgba(0, 0, 0, 0.6); font-size: 13px; font-weight: 400; text-align: center; padding: 0;" valign="top" align="center">\r\n                                                                By CTVC &#x2022; <span class="post-meta-date" style="white-space: nowrap;">14 Jul 2025 </span>\r\n                                                            </td>\r\n                                                            <td class="post-meta post-meta-center view-online desktop" style="font-family: -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif; vertical-align: top; color: rgba(0, 0, 0, 0.6); font-size: 13px; font-weight: 400; text-align: center; display: none;" valign="top" align="center">\r\n                                                                <a href="https://www.ctvc.co/r/0e13332c?m=fa154ea2-883d-4569-a2d8-205feec38852" class="view-online-link" style="word-wrap: none; white-space: nowrap; color: #15212a; color: rgba(0, 0, 0, 0.6); overflow-wrap: anywhere; text-decoration: underline;" target="_blank">View in browser</a>\r\n                                                            </td>\r\n                                                        </tr>\r\n                                                        <tr class="post-meta post-meta-center view-online-mobile" style="color: #15212a; color: rgba(0, 0, 0, 0.6); font-size: 13px; font-weight: 400; text-align: center;" align="center">\r\n                                                            <td height="20" class="view-online" style="font-fam

In [38]:
import pandas as pd

companies = pd.read_csv("private_data/companies.csv")[["Company","Domain","Location","Tagline","Investors"]]
enrich_companies = pd.read_csv("private_data/enrich_companies.csv")
for index, row in enrich_companies.iterrows():
    enrich_location = row["Location"]
    enrich_investors = row["Investors"]
    if pd.isna(enrich_location):
        enrich_companies.at[index,"Location"] = companies.loc[index,"Location"]
    if pd.isna(enrich_investors):
        enrich_companies.at[index,"Investors"] = companies.loc[index,"Investors"]

In [39]:
enrich_companies.to_csv("private_data/enrich_companies.csv")

In [58]:
from affinity import affinity_enrich
# Count companies not in Affinity
not_found_companies = enrich_companies[enrich_companies["Affinty ID"] == "Not in Affinity"].shape[0]

# Iterate through enrich_companies
count = 1
for index, row in enrich_companies.iterrows():
    if row["Affinty ID"] == "Not in Affinity":
        # if count%5==0:
        print(f"Processing {count}/{not_found_companies}")
        info_for_enrich = (
            row["name"],
            row["Location"],
            row["domain"],
            row["id"],
            row["tagline"],
            row["Investors"]
        )
        
        # Enrich
        result = affinity_enrich(info_for_enrich, 0)

        # Update row in DataFrame
        for key, value in result.items():
            if key in enrich_companies.columns:
                enrich_companies.at[index, key] = value
        count+=1
        # break  # remove this if you want to run on ALL not-in-Affinity entries

Processing 1/1468
Processing 2/1468
Processing 3/1468
Processing 4/1468
Processing 5/1468
Processing 6/1468
Processing 7/1468
Processing 8/1468
Processing 9/1468
Processing 10/1468
Processing 11/1468
Processing 12/1468
Processing 13/1468
Processing 14/1468
Processing 15/1468
Processing 16/1468
Processing 17/1468
Processing 18/1468
Processing 19/1468
Processing 20/1468
Processing 21/1468
Processing 22/1468
Processing 23/1468
Processing 24/1468
Processing 25/1468
Processing 26/1468
Processing 27/1468
Processing 28/1468
Processing 29/1468
Processing 30/1468
Processing 31/1468
Processing 32/1468
Processing 33/1468
Processing 34/1468
Processing 35/1468
Processing 36/1468
Processing 37/1468
Processing 38/1468
Processing 39/1468
Processing 40/1468
Processing 41/1468
Processing 42/1468
Processing 43/1468
Processing 44/1468
Processing 45/1468
Processing 46/1468
Processing 47/1468
Processing 48/1468
Processing 49/1468
Processing 50/1468
Processing 51/1468
Processing 52/1468
Processing 53/1468
Processing 54/1468
Processing 55/1468
Processing 56/1468
Processing 57/1468
Processing 58/1468
Processing 59/1468
Processing 60/1468
Processing 61/1468
Processing 62/1468
Processing 63/1468
Processing 64/1468
Processing 65/1468
Processing 66/1468
Processing 67/1468
Processing 68/1468
Processing 69/1468
Processing 70/1468
Processing 71/1468
Processing 72/1468
Processing 73/1468
Processing 74/1468
Processing 75/1468
Processing 76/1468
Processing 77/1468
Processing 78/1468
Processing 79/1468
Processing 80/1468
Processing 81/1468
Processing 82/1468
Processing 83/1468
Processing 84/1468
Processing 85/1468
Processing 86/1468
Processing 87/1468
Processing 88/1468
Processing 89/1468
Processing 90/1468
Processing 91/1468
Processing 92/1468
Processing 93/1468
Processing 94/1468
Processing 95/1468
Processing 96/1468
Processing 97/1468
Processing 98/1468
Processing 99/1468
Processing 100/1468
Processing 101/1468
Processing 102/1468
Processing 103/1468
Processing 104/1468
Processing 105/1468
Processing 106/1468
Processing 107/1468
Processing 108/1468
Processing 109/1468
Processing 110/1468
Processing 111/1468
Processing 112/1468
Processing 113/1468
Processing 114/1468
Processing 115/1468
Processing 116/1468
Processing 117/1468
Processing 118/1468
Processing 119/1468
Processing 120/1468
Processing 121/1468
Processing 122/1468
Processing 123/1468
Processing 124/1468
Processing 125/1468
Processing 126/1468
Processing 127/1468
Processing 128/1468
Processing 129/1468
Processing 130/1468
Processing 131/1468
Processing 132/1468
Processing 133/1468
Processing 134/1468
Processing 135/1468
Processing 136/1468
Processing 137/1468
Processing 138/1468
Processing 139/1468
Processing 140/1468
Processing 141/1468
Processing 142/1468
Processing 143/1468
Processing 144/1468
Processing 145/1468
Processing 146/1468
Processing 147/1468
Processing 148/1468
Processing 149/1468
Processing 150/1468
Processing 151/1468
Processing 152/1468
Processing 153/1468
Processing 154/1468
Processing 155/1468
Processing 156/1468
Processing 157/1468
Processing 158/1468
Processing 159/1468
Processing 160/1468
Processing 161/1468
Processing 162/1468
Processing 163/1468
Processing 164/1468
Processing 165/1468
Processing 166/1468
Processing 167/1468
Processing 168/1468
Processing 169/1468
Processing 170/1468
Processing 171/1468
Processing 172/1468
Processing 173/1468
Processing 174/1468
Processing 175/1468
Processing 176/1468
Processing 177/1468
Processing 178/1468
Processing 179/1468
Processing 180/1468
Processing 181/1468
Processing 182/1468
Processing 183/1468
Processing 184/1468
Processing 185/1468
Processing 186/1468
Processing 187/1468
Processing 188/1468
Processing 189/1468
Processing 190/1468
Processing 191/1468
Processing 192/1468
Processing 193/1468
Processing 194/1468
Processing 195/1468
Processing 196/1468
Processing 197/1468
Processing 198/1468
Processing 199/1468
Processing 200/1468
Processing 201/1468
Processing 202/1468
Processing 203/1468
Processing 204/1468
Processing 205/1468
Processing 206/1468
Processing 207/1468
Processing 208/1468
Processing 209/1468
Processing 210/1468
Processing 211/1468
Processing 212/1468
Processing 213/1468
Processing 214/1468
Processing 215/1468
Processing 216/1468
Processing 217/1468
Processing 218/1468
Processing 219/1468
Processing 220/1468
Processing 221/1468
Processing 222/1468
Processing 223/1468
Processing 224/1468
Processing 225/1468
Processing 226/1468
Processing 227/1468
Processing 228/1468
Processing 229/1468
Processing 230/1468
Processing 231/1468
Processing 232/1468
Processing 233/1468
Processing 234/1468
Processing 235/1468
Processing 236/1468
Processing 237/1468
Processing 238/1468
Processing 239/1468
Processing 240/1468
Processing 241/1468
Processing 242/1468
Processing 243/1468
Processing 244/1468
Processing 245/1468
Processing 246/1468
Processing 247/1468
Processing 248/1468
Processing 249/1468
Processing 250/1468
Processing 251/1468
Processing 252/1468
Processing 253/1468
Processing 254/1468
Processing 255/1468
Processing 256/1468
Processing 257/1468
Processing 258/1468
Processing 259/1468
Processing 260/1468
Processing 261/1468
Processing 262/1468
Processing 263/1468
Processing 264/1468
Processing 265/1468
Processing 266/1468
Processing 267/1468
Processing 268/1468
Processing 269/1468
Processing 270/1468
Processing 271/1468
Processing 272/1468
Processing 273/1468
Processing 274/1468
Processing 275/1468
Processing 276/1468
Processing 277/1468
Processing 278/1468
Processing 279/1468
Processing 280/1468
Processing 281/1468
Processing 282/1468
Processing 283/1468
Processing 284/1468
Processing 285/1468
Processing 286/1468
Processing 287/1468
Processing 288/1468
Processing 289/1468
Processing 290/1468
Processing 291/1468
Processing 292/1468
Processing 293/1468
Processing 294/1468
Processing 295/1468
Processing 296/1468
Processing 297/1468
Processing 298/1468
Processing 299/1468
Processing 300/1468
Processing 301/1468
Processing 302/1468
Processing 303/1468
Processing 304/1468
Processing 305/1468
Processing 306/1468
Processing 307/1468
Processing 308/1468
Processing 309/1468
Processing 310/1468
Processing 311/1468
Processing 312/1468
Processing 313/1468
Processing 314/1468
Processing 315/1468
Processing 316/1468
Processing 317/1468
Processing 318/1468
Processing 319/1468
Processing 320/1468
Processing 321/1468
Processing 322/1468
Processing 323/1468
Processing 324/1468
Processing 325/1468
Processing 326/1468
Processing 327/1468
Processing 328/1468
Processing 329/1468
Processing 330/1468
Processing 331/1468
Processing 332/1468
Processing 333/1468
Processing 334/1468
Processing 335/1468
Processing 336/1468
Processing 337/1468
Processing 338/1468
Processing 339/1468
Processing 340/1468
Processing 341/1468
Processing 342/1468
Processing 343/1468
Processing 344/1468
Processing 345/1468
Processing 346/1468
Processing 347/1468
Processing 348/1468
Processing 349/1468
Processing 350/1468
Processing 351/1468
Processing 352/1468
Processing 353/1468
Processing 354/1468
Processing 355/1468
Processing 356/1468
Processing 357/1468
Processing 358/1468
Processing 359/1468
Processing 360/1468
Processing 361/1468
Processing 362/1468
Processing 363/1468
Processing 364/1468
Processing 365/1468
Processing 366/1468
Processing 367/1468
Processing 368/1468
Processing 369/1468
Processing 370/1468
Processing 371/1468
Processing 372/1468
Processing 373/1468
Processing 374/1468
Processing 375/1468
Processing 376/1468
Processing 377/1468
Processing 378/1468
Processing 379/1468
Processing 380/1468
Processing 381/1468
Processing 382/1468
Processing 383/1468
Processing 384/1468
Processing 385/1468
Processing 386/1468
Processing 387/1468
Processing 388/1468
Processing 389/1468
Processing 390/1468
Processing 391/1468
Processing 392/1468
Processing 393/1468
Processing 394/1468
Processing 395/1468
Processing 396/1468
Processing 397/1468
Processing 398/1468
Processing 399/1468
Processing 400/1468
Processing 401/1468
Processing 402/1468
Processing 403/1468
Processing 404/1468
Processing 405/1468
Processing 406/1468
Processing 407/1468
Processing 408/1468
Processing 409/1468
Processing 410/1468
Processing 411/1468
Processing 412/1468
Processing 413/1468
Processing 414/1468
Processing 415/1468
Processing 416/1468
Processing 417/1468
Processing 418/1468
Processing 419/1468
Processing 420/1468
Processing 421/1468
Processing 422/1468
Processing 423/1468
Processing 424/1468
Processing 425/1468
Processing 426/1468
Processing 427/1468
Processing 428/1468
Processing 429/1468
Processing 430/1468
Processing 431/1468
Processing 432/1468
Processing 433/1468
Processing 434/1468
Processing 435/1468
Processing 436/1468
Processing 437/1468
Processing 438/1468
Processing 439/1468
Processing 440/1468
Processing 441/1468
Processing 442/1468
Processing 443/1468
Processing 444/1468
Processing 445/1468
Processing 446/1468
Processing 447/1468
Processing 448/1468
Processing 449/1468
Processing 450/1468
Processing 451/1468
Processing 452/1468
Processing 453/1468
Processing 454/1468
Processing 455/1468
Processing 456/1468
Processing 457/1468
Processing 458/1468
Processing 459/1468
Processing 460/1468
Processing 461/1468
Processing 462/1468
Processing 463/1468
Processing 464/1468
Processing 465/1468
Processing 466/1468
Processing 467/1468
Processing 468/1468
Processing 469/1468
Processing 470/1468
Processing 471/1468
Processing 472/1468
Processing 473/1468
Processing 474/1468
Processing 475/1468
Processing 476/1468
Processing 477/1468
Processing 478/1468
Processing 479/1468
Processing 480/1468
Processing 481/1468
Processing 482/1468
Processing 483/1468
Processing 484/1468
Processing 485/1468
Processing 486/1468
Processing 487/1468
Processing 488/1468
Processing 489/1468
Processing 490/1468
Processing 491/1468
Processing 492/1468
Processing 493/1468
Processing 494/1468
Processing 495/1468
Processing 496/1468
Processing 497/1468
Processing 498/1468
Processing 499/1468
Processing 500/1468
Processing 501/1468
Processing 502/1468
Processing 503/1468
Processing 504/1468
Processing 505/1468
Processing 506/1468
Processing 507/1468
Processing 508/1468
Processing 509/1468
Processing 510/1468
Processing 511/1468
Processing 512/1468
Processing 513/1468
Processing 514/1468
Processing 515/1468
Processing 516/1468
Processing 517/1468
Processing 518/1468
Processing 519/1468
Processing 520/1468
Processing 521/1468
Processing 522/1468
Processing 523/1468
Processing 524/1468
Processing 525/1468
Processing 526/1468
Processing 527/1468
Processing 528/1468
Processing 529/1468
Processing 530/1468
Processing 531/1468
Processing 532/1468
Processing 533/1468
Processing 534/1468
Processing 535/1468
Processing 536/1468
Processing 537/1468
Processing 538/1468
Processing 539/1468
Processing 540/1468
Processing 541/1468
Processing 542/1468
Processing 543/1468
Processing 544/1468
Processing 545/1468
Processing 546/1468
Processing 547/1468
Processing 548/1468
Processing 549/1468
Processing 550/1468
Processing 551/1468
Processing 552/1468
Processing 553/1468
Processing 554/1468
Processing 555/1468
Processing 556/1468
Processing 557/1468
Processing 558/1468
Processing 559/1468
Processing 560/1468
Processing 561/1468
Processing 562/1468
Processing 563/1468
Processing 564/1468
Processing 565/1468
Processing 566/1468
Processing 567/1468
Processing 568/1468
Processing 569/1468
Processing 570/1468
Processing 571/1468
Processing 572/1468
Processing 573/1468
Processing 574/1468
Processing 575/1468
Processing 576/1468
Processing 577/1468
Processing 578/1468
Processing 579/1468
Processing 580/1468
Processing 581/1468
Processing 582/1468
Processing 583/1468
Processing 584/1468
Processing 585/1468
Processing 586/1468
Processing 587/1468
Processing 588/1468
Processing 589/1468
Processing 590/1468
Processing 591/1468
Processing 592/1468
Processing 593/1468
Processing 594/1468
Processing 595/1468
Processing 596/1468
Processing 597/1468
Processing 598/1468
Processing 599/1468
Processing 600/1468
Processing 601/1468
Processing 602/1468
Processing 603/1468
Processing 604/1468
Processing 605/1468
Processing 606/1468
Processing 607/1468
Processing 608/1468
Processing 609/1468
Processing 610/1468
Processing 611/1468
Processing 612/1468
Processing 613/1468
Processing 614/1468
Processing 615/1468
Processing 616/1468
Processing 617/1468
Processing 618/1468
Processing 619/1468
Processing 620/1468
Processing 621/1468
Processing 622/1468
Processing 623/1468
Processing 624/1468
Processing 625/1468
Processing 626/1468
Processing 627/1468
Processing 628/1468
Processing 629/1468
Processing 630/1468
Processing 631/1468
Processing 632/1468
Processing 633/1468
Processing 634/1468
Processing 635/1468
Processing 636/1468
Processing 637/1468
Processing 638/1468
Processing 639/1468
Processing 640/1468
Processing 641/1468
Processing 642/1468
Processing 643/1468
Processing 644/1468
Processing 645/1468
Processing 646/1468
Processing 647/1468
Processing 648/1468
Processing 649/1468
Processing 650/1468
Processing 651/1468
Processing 652/1468
Processing 653/1468
Processing 654/1468
Processing 655/1468
Processing 656/1468
Processing 657/1468
Processing 658/1468
Processing 659/1468
Processing 660/1468
Processing 661/1468
Processing 662/1468
Processing 663/1468
Processing 664/1468
Processing 665/1468
Processing 666/1468
Processing 667/1468
Processing 668/1468
Processing 669/1468
Processing 670/1468
Processing 671/1468
Processing 672/1468
Processing 673/1468
Processing 674/1468
Processing 675/1468
Processing 676/1468
Processing 677/1468
Processing 678/1468
Processing 679/1468
Processing 680/1468
Processing 681/1468
Processing 682/1468
Processing 683/1468
Processing 684/1468
Processing 685/1468
Processing 686/1468
Processing 687/1468
Processing 688/1468
Processing 689/1468
Processing 690/1468
Processing 691/1468
Processing 692/1468
Processing 693/1468
Processing 694/1468
Processing 695/1468
Processing 696/1468
Processing 697/1468
Processing 698/1468
Processing 699/1468
Processing 700/1468
Processing 701/1468
Processing 702/1468
Processing 703/1468
Processing 704/1468
Processing 705/1468
Processing 706/1468
Processing 707/1468
Processing 708/1468
Processing 709/1468
Processing 710/1468
Processing 711/1468
Processing 712/1468
Processing 713/1468
Processing 714/1468
Processing 715/1468
Processing 716/1468
Processing 717/1468
Processing 718/1468
Processing 719/1468
Processing 720/1468
Processing 721/1468
Processing 722/1468
Processing 723/1468
Processing 724/1468
Processing 725/1468
Processing 726/1468
Processing 727/1468
Processing 728/1468
Processing 729/1468
Processing 730/1468
Processing 731/1468
Processing 732/1468
Processing 733/1468
Processing 734/1468
Processing 735/1468
Processing 736/1468
Processing 737/1468
Processing 738/1468
Processing 739/1468
Processing 740/1468
Processing 741/1468
Processing 742/1468
Processing 743/1468
Processing 744/1468
Processing 745/1468
Processing 746/1468
Processing 747/1468
Processing 748/1468
Processing 749/1468
Processing 750/1468
Processing 751/1468
Processing 752/1468
Processing 753/1468
Processing 754/1468
Processing 755/1468
Processing 756/1468
Processing 757/1468
Processing 758/1468
Processing 759/1468
Processing 760/1468
Processing 761/1468
Processing 762/1468
Processing 763/1468
Processing 764/1468
Processing 765/1468
Processing 766/1468
Processing 767/1468
Processing 768/1468
Processing 769/1468
Processing 770/1468
Processing 771/1468
Processing 772/1468
Processing 773/1468
Processing 774/1468
Processing 775/1468
Processing 776/1468
Processing 777/1468
Processing 778/1468
Processing 779/1468
Processing 780/1468
Processing 781/1468
Processing 782/1468
Processing 783/1468
Processing 784/1468
Processing 785/1468
Processing 786/1468
Processing 787/1468
Processing 788/1468
Processing 789/1468
Processing 790/1468
Processing 791/1468
Processing 792/1468
Processing 793/1468
Processing 794/1468
Processing 795/1468
Processing 796/1468
Processing 797/1468
Processing 798/1468
Processing 799/1468
Processing 800/1468
Processing 801/1468
Processing 802/1468
Processing 803/1468
Processing 804/1468
Processing 805/1468
Processing 806/1468
Processing 807/1468
Processing 808/1468
Processing 809/1468
Processing 810/1468
Processing 811/1468
Processing 812/1468
Processing 813/1468
Processing 814/1468
Processing 815/1468
Processing 816/1468
Processing 817/1468
Processing 818/1468
Processing 819/1468
Processing 820/1468
Processing 821/1468
Processing 822/1468
Processing 823/1468
Processing 824/1468
Processing 825/1468
Processing 826/1468
Processing 827/1468
Processing 828/1468
Processing 829/1468
Processing 830/1468
Processing 831/1468
Processing 832/1468
Processing 833/1468
Processing 834/1468
Processing 835/1468
Processing 836/1468
Processing 837/1468
Processing 838/1468
Processing 839/1468
Processing 840/1468
Processing 841/1468
Processing 842/1468
Processing 843/1468
Processing 844/1468
Processing 845/1468
Processing 846/1468
Processing 847/1468
Processing 848/1468
Processing 849/1468
Processing 850/1468
Processing 851/1468
Processing 852/1468
Processing 853/1468
Processing 854/1468
Processing 855/1468
Processing 856/1468
Processing 857/1468
Processing 858/1468
Processing 859/1468
Processing 860/1468
Processing 861/1468
Processing 862/1468
Processing 863/1468
Processing 864/1468
Processing 865/1468
Processing 866/1468
Processing 867/1468
Processing 868/1468
Processing 869/1468
Processing 870/1468
Processing 871/1468
Processing 872/1468
Processing 873/1468
Processing 874/1468
Processing 875/1468
Processing 876/1468
Processing 877/1468
Processing 878/1468
Processing 879/1468
Processing 880/1468
Processing 881/1468
Processing 882/1468
Processing 883/1468
Processing 884/1468
Processing 885/1468
Processing 886/1468
Processing 887/1468
Processing 888/1468
Processing 889/1468
Processing 890/1468
Processing 891/1468
Processing 892/1468
Processing 893/1468
Processing 894/1468
Processing 895/1468
Processing 896/1468
Processing 897/1468
Processing 898/1468
Processing 899/1468
Processing 900/1468
Processing 901/1468
Processing 902/1468
Processing 903/1468
Processing 904/1468
Processing 905/1468
Processing 906/1468
Processing 907/1468
Processing 908/1468
Processing 909/1468
Processing 910/1468
Processing 911/1468
Processing 912/1468
Processing 913/1468
Processing 914/1468
Processing 915/1468
Processing 916/1468
Processing 917/1468
Processing 918/1468
Processing 919/1468
Processing 920/1468
Processing 921/1468
Processing 922/1468
Processing 923/1468
Processing 924/1468
Processing 925/1468
Processing 926/1468
Processing 927/1468
Processing 928/1468
Processing 929/1468
Processing 930/1468
Processing 931/1468
Processing 932/1468
Processing 933/1468
Processing 934/1468
Processing 935/1468
Processing 936/1468
Processing 937/1468
Processing 938/1468
Processing 939/1468
Processing 940/1468
Processing 941/1468
Processing 942/1468
Processing 943/1468
Processing 944/1468
Processing 945/1468
Processing 946/1468
Processing 947/1468
Processing 948/1468
Processing 949/1468
Processing 950/1468
Processing 951/1468
Processing 952/1468
Processing 953/1468
Processing 954/1468
Processing 955/1468
Processing 956/1468
Processing 957/1468
Processing 958/1468
Processing 959/1468
Processing 960/1468
Processing 961/1468
Processing 962/1468
Processing 963/1468
Processing 964/1468
Processing 965/1468
Processing 966/1468
Processing 967/1468
Processing 968/1468
Processing 969/1468
Processing 970/1468
Processing 971/1468
Processing 972/1468
Processing 973/1468
Processing 974/1468
Processing 975/1468
Processing 976/1468
Processing 977/1468
Processing 978/1468
Processing 979/1468
Processing 980/1468
Processing 981/1468
Processing 982/1468
Processing 983/1468
Processing 984/1468
Processing 985/1468
Processing 986/1468
Processing 987/1468
Processing 988/1468
Processing 989/1468
Processing 990/1468
Processing 991/1468
Processing 992/1468
Processing 993/1468
Processing 994/1468
Processing 995/1468
Processing 996/1468
Processing 997/1468
Processing 998/1468
Processing 999/1468
Processing 1000/1468
Processing 1001/1468
Processing 1002/1468
Processing 1003/1468
Processing 1004/1468
Processing 1005/1468

In [8]:
import pandas as pd
import os 

enrich_companies = pd.read_csv("private_data/enriched_companies.csv")

In [9]:
enrich_companies[enrich_companies["Affinty ID"] == "Not in Affinity"]

,Unnamed: 0,id,name,tagline,domain,Location,Investors,Employees (Current),Employees: Growth YoY (%),Investment Stage,Last Funding Amount (USD),LinkedIn Profile (Founders/CEOs),In Energize Affinity,Affinty ID
1,1,ca38d2f4-157d-4146-a67e-9df8d5e3d72b,11x,AI autonomous digital workers developer,https://www.11x.com/,"San Francisco, CA","[' sv angel', ' quiet capital', 'benchmark', '...",NaN,NaN,NaN,NaN,NaN,False,Not in Affinity
4,4,a5dcbe42-0f73-4697-b9bf-ad1b08e1637b,1mt nation,Developer of nature-based carbon removal projects,NaN,"Tallinn, Estonia","[' warmeston', 'margus kohava']",NaN,NaN,NaN,NaN,NaN,False,Not in Affinity
10,10,38af1a43-6956-4c88-a073-fe52657babda,257,AI-powered home energy management software,NaN,"New York, New York",['f2 venture capital'],NaN,NaN,NaN,NaN,NaN,False,Not in Affinity
16,16,2221eb02-6e36-4275-9bce-f8cd4bb78846,44.01,Carbon removal and mineralization technologies,NaN,"London, U.K.","['nysnø climate investments', 'equinor venture...",NaN,NaN,NaN,NaN,NaN,False,Not in Affinity
17,17,74c55a8d-682f-4ee9-9755-1175081724aa,4elements,Launch of new high-impact climate startups,NaN,"TK, France",[],NaN,NaN,NaN,NaN,NaN,False,Not in Affinity
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4513,4513,5a25b043-478a-445a-8555-8d0a6ffc4b3c,zikooin,Provider of meat alternatives,NaN,South Korea,['mostly us venture firms'],NaN,NaN,NaN,NaN,NaN,False,Not in Affinity
4519,4519,409ead0f-640b-4954-8b1b-8badf3de00e6,zoomo,Maker of electric last-mile delivery vehicles,NaN,Australia,"[' contrarian ventures', 'collaborative fund',...",NaN,NaN,NaN,NaN,NaN,False,Not in Affinity
4520,4520,aeb715e9-0491-4002-b470-f5ecce542747,zordi,Autonomous greenhouse developer,NaN,"Boston, MA",['khosla ventures'],NaN,NaN,NaN,NaN,NaN,False,Not in Affinity
4527,4527,955465a8-1e8f-49e2-aafe-8c75b0172742,zyngo ev,Sustainable last-mile solutions company,NaN,"Haryana, India","['delta corp holdings', ' lc nueva investment ...",NaN,NaN,NaN,NaN,NaN,False,Not in Affinity
4528,4528,deeef6fb-e35d-4f66-8b52-fbd42c30bef0,zypp electric,Last-mile delivery EV rental service,NaN,"Gurugram, India","[' venture catalysts', ' ivy growth associates...",NaN,NaN,NaN,NaN,NaN,False,Not in Affinity

In [40]:
from config import OPENAI_API_KEY, SUPABASE_API_KEY,SUPABASE_API_URL
from supabase import create_client, Client
from openai import OpenAI
import pandas as pd

client = OpenAI()

supabase: Client = create_client(SUPABASE_API_URL,SUPABASE_API_KEY)

def build_embedding_text(row):
    parts = [
        f"Company: {row['name']}",
        f"Tagline: {row['tagline'] or ''}",
        f"Domain: {row['domain'] or ''}",
        f"Location: {row['Location'] or ''}",
        f"Industry: {row['Industry'] or ''}",
        f"Investors: {row['Investors'] or ''}",
    ]
    return "\n".join([p for p in parts if p.strip()])

def fetch_all_companies_without_embeddings(batch_size=1000, max_rows=5000):
    all_rows = []
    for offset in range(0, max_rows, batch_size):
        response = supabase.table("companies")\
            .select("*")\
            .filter("embedding", "is", "null")\
            .range(offset, offset + batch_size - 1)\
            .execute()

        rows = response.data
        if not rows:
            break  # Exit early if no more results
        all_rows.extend(rows)

    return all_rows


def generate_embedding(text):
    response = client.embeddings.create(
        model="text-embedding-3-small",
        input=text
    )
    return response.data[0].embedding

def update_embedding(company_id, embedding_vector):
    supabase.table("companies").update({
        "embedding": embedding_vector
    }).eq("id", company_id).execute()

def embed_batch():
    rows = fetch_all_companies_without_embeddings()
    for index, row in enumerate(rows):
        try:
            text = build_embedding_text(row)
            embedding = generate_embedding(text)
            update_embedding(row["id"], embedding)
            if index%20==0:
                print(f"processing {index}/{len(rows)}")
                print(f"✅ Embedded: {row['name']}")
        except Exception as e:
            print(f"❌ Error on {row['id']}: {e}")

df = pd.DataFrame(fetch_all_companies_without_embeddings())

In [41]:
df

,id,name,tagline,domain,Location,Investors,Employees (Current),Employees: Growth YoY (%),Investment Stage,Last Funding Amount (USD),LinkedIn Profile (Founders/CEOs),In Energize Affinity,Affinity ID,Industry,Business Models,Technologies,embedding
0,447ce3ec-66ef-42bb-b9e5-406c8673b6a1,Aether Fuels,Sustainable aviation fuel developer,aetherfuels.com,"Chicago, Illinois","['TechEnergy Ventures', 'Xora Innovation', 'Fo...",28.0,27.27,Series A,34000000.0,Conor Madigan (Founder and CEO): https://linke...,True,290082831,"['Transportation', 'Energy', 'Clean Energy']",Manufacturing,Hardware,None
1,69e7dc0a-f0ce-4bac-acca-f3a3c946c1ad,Aetherflux,Network of small satellites designed to collec...,aetherflux.com,"San Francisco, California","['others', 'Interlagos', 'Index Ventures', 'NE...",10.0,NaN,Series A,50000000.0,None,True,296564490,"['Space', 'Energy', 'Clean Energy']",Manufacturing,None,None
2,0921776b-48e1-49a7-ad2f-4976a656b430,Applied EV,Modular autonomous electric vehicle maker,aevrobotics.com,Australia,,NaN,NaN,None,NaN,None,False,291892991,None,None,None,None
3,453a406b-0163-4c94-98ab-fdb39bce8f10,Aeva,LiDAR sensing and perception technologies,aeva.com,"Mountain View, CA",['sylebra capital'],NaN,NaN,None,NaN,None,False,291723026,None,None,None,None
4,8f4b774d-0a70-4743-8685-f96947f284c4,afresh,AI company developing food technology that pre...,https://freshbus.in/,"San Francisco, CA","[' shell ventures', ' bright pixel', ' alteria...",NaN,NaN,None,NaN,None,False,Not in Affinity,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4385,e8a7e737-9de6-4d07-a81b-5862c52fdb40,ZwitterCo,Fouling-resistant membrane technologies provider,zwitterco.com,"Woburn, Massachusetts","['Genoa Ventures', 'Heritage Group Ventures', ...",66.0,-2.94,Series B,58400000.0,['Christopher Drover (CTO & Co-Founder): https...,True,198217648,"['Energy', 'Water', 'Waste Solution']",Manufacturing,None,None
4386,aaf88137-a2a4-4eba-975e-344f65abb453,Zymofix,Solid-state fermentation technology for fertil...,zymofix.com,"Ghent, Belgium",['high-tech gründerfonds'],NaN,NaN,None,NaN,None,False,299792881,None,None,None,None
4387,26398d63-642d-4fc1-88fd-81c9669707af,Zymvol Biomodeling,Biotech enzyme discovery platform,zymvol.com,"Barcelona, Spain","['Elaia Partners', 'Faber', 'Übermorgen Ventur...",35.0,-7.89,Seed,3000000.0,['Emanuele Monza (Co-founder & Chief Scientifi...,True,142375942,"['Health', 'Pharmaceutical', 'BioTechnology']",Manufacturing,"['Hardware', 'Deep Tech', 'Quantum Technologies']",None
4388,955465a8-1e8f-49e2-aafe-8c75b0172742,zyngo ev,Sustainable last-mile solutions company,None,"Haryana, India","['delta corp holdings', ' lc nueva investment ...",NaN,NaN,None,NaN,None,False,Not in Affinity,None,None,None,None
4389,deeef6fb-e35d-4f66-8b52-fbd42c30bef0,zypp electric,Last-mile delivery EV rental service,None,"Gurugram, India","[' venture catalysts', ' ivy growth associates...",NaN,NaN,None,NaN,None,False,Not in Affinity,None,None,None,None

In [42]:
embed_batch()

processing 0/4390
✅ Embedded: Aether Fuels
processing 20/4390
✅ Embedded: AgriTask
processing 40/4390
✅ Embedded: Aigen
processing 60/4390
✅ Embedded: Aligned Climate Capital
processing 80/4390
✅ Embedded: algama
processing 100/4390
✅ Embedded: Alrik
processing 120/4390
✅ Embedded: aluna
processing 140/4390
✅ Embedded: Ampacimon
processing 160/4390
✅ Embedded: Anodot
processing 180/4390
✅ Embedded: Applied Carbon
processing 200/4390
✅ Embedded: Arbor
processing 220/4390
✅ Embedded: Arevo AB
processing 240/4390
✅ Embedded: Ascend Elements
processing 260/4390
✅ Embedded: Ati Motors
processing 280/4390
✅ Embedded: Augmentus
processing 300/4390
✅ Embedded: avant
processing 320/4390
✅ Embedded: bacta
processing 340/4390
✅ Embedded: BatX Energies
processing 360/4390
✅ Embedded: Bees & Bears
processing 380/4390
✅ Embedded: Bevi
processing 400/4390
✅ Embedded: Bioeutectics
processing 420/4390
✅ Embedded: Blackhorn Ventures
processing 440/4390
✅ Embedded: Blue Planet Energy Systems, LLC
processing 460/4390
✅ Embedded: BlueRedGold
processing 480/4390
✅ Embedded: Bond Pet Foods
processing 500/4390
✅ Embedded: brasol
processing 520/4390
✅ Embedded: Briink
processing 540/4390
✅ Embedded: Built Robotics
processing 560/4390
✅ Embedded: Cactos
processing 580/4390
✅ Embedded: cameo
processing 600/4390
✅ Embedded: carbmee
processing 620/4390
✅ Embedded: carbon ridge
processing 640/4390
✅ Embedded: CarbonPool
processing 660/4390
✅ Embedded: website
processing 680/4390
✅ Embedded: CellMEAT
processing 700/4390
✅ Embedded: Charge
processing 720/4390
✅ Embedded: Chilibeli
processing 740/4390
✅ Embedded: Circadian Technologies
processing 760/4390
✅ Embedded: Clarity AI
processing 780/4390
✅ Embedded: CleanRobotics
processing 800/4390
✅ Embedded: ClimateAI
processing 820/4390
✅ Embedded: Cloud Paper
processing 840/4390
✅ Embedded: Codat
processing 860/4390
✅ Embedded: Compact Membrane Systems
processing 880/4390
✅ Embedded: Connect Homes
processing 900/4390
✅ Embedded: Copernic Catalysts
processing 920/4390
✅ Embedded: cosmic robotics
processing 940/4390
✅ Embedded: Crop Enhancement
processing 960/4390
✅ Embedded: Cumul.io
processing 980/4390
✅ Embedded: CYNGN
processing 1000/4390
✅ Embedded: databutton
processing 1020/4390
✅ Embedded: debut
processing 1040/4390
✅ Embedded: delta green
processing 1060/4390
✅ Embedded: dharaksha ecosolutions
processing 1080/4390
✅ Embedded: domna
processing 1100/4390
✅ Embedded: Dunia
processing 1120/4390
✅ Embedded: e2 Companies
processing 1140/4390
✅ Embedded: eclipse foods
processing 1160/4390
✅ Embedded: ecolution kwh
processing 1180/4390
✅ Embedded: Eco Wave Power
processing 1200/4390
✅ Embedded: EINHUNDERT Energie
processing 1220/4390
✅ Embedded: Electric Era
processing 1240/4390
✅ Embedded: element3
processing 1260/4390
✅ Embedded: Emidat
processing 1280/4390
✅ Embedded: Enduro Genetics
processing 1300/4390
✅ Embedded: Enerkem
processing 1320/4390
✅ Embedded: Enpal Italy
processing 1340/4390
✅ Embedded: EnZinc Inc
processing 1360/4390
✅ Embedded: EquipmentShare
processing 1380/4390
✅ Embedded: etch
processing 1400/4390
✅ Embedded: evera
processing 1420/4390
✅ Embedded: evolutionaryscale
processing 1440/4390
✅ Embedded: Extantia Capital
processing 1460/4390
✅ Embedded: farm-ng
processing 1480/4390
✅ Embedded: Fero Labs
processing 1500/4390
✅ Embedded: Finite Carbon
processing 1520/4390
✅ Embedded: Flashfood
processing 1540/4390
✅ Embedded: floodbase
processing 1560/4390
✅ Embedded: Flyscan
processing 1580/4390
✅ Embedded: forward earth
processing 1600/4390
✅ Embedded: Freterium
processing 1620/4390
✅ Embedded: Fungu'it
processing 1640/4390
✅ Embedded: gaeastar
processing 1660/4390
✅ Embedded: GEF Capital Partners
processing 1680/4390
✅ Embedded: Geox S p A
processing 1700/4390
✅ Embedded: goEgoNetwork
processing 1720/4390
✅ Embedded: gradiant
processing 1740/4390
✅ Embedded: green energy park
processing 1760/4390
✅ Embedded: GreenLight Biosciences
processing 1780/4390
✅ Embedded: GridFree AI
processing 1800/4390
✅ Embedded: Group14 Technologies
processing 1820/4390
✅ Embedded: H2scan
processing 1840/4390
✅ Embedded: harvest thermal
processing 1860/4390
✅ Embedded: Heila Technologies
processing 1880/4390
✅ Embedded: Ideal Semiconductor Devices
processing 1900/4390
✅ Embedded: Hoofprint Biome
processing 1920/4390
✅ Embedded: hybrid energy
processing 1940/4390
✅ Embedded: hypermotive
processing 1960/4390
✅ Embedded: ieqsy
processing 1980/4390
✅ Embedded: In Ovo
processing 2000/4390
✅ Embedded: InfluxData
processing 2020/4390
✅ Embedded: insolight
processing 2040/4390
✅ Embedded: Intello Labs
processing 2060/4390
✅ Embedded: Ion Storage Systems
processing 2080/4390
✅ Embedded: Isometric
processing 2100/4390
✅ Embedded: Jolt Energy
processing 2120/4390
✅ Embedded: Kapta Space
processing 2140/4390
✅ Embedded: Kilimo
processing 2160/4390
✅ Embedded: Kodiak Robotics
processing 2180/4390
✅ Embedded: kusaridev
processing 2200/4390
✅ Embedded: LanzaJet
processing 2220/4390
✅ Embedded: LevelTen Energy
processing 2240/4390
✅ Embedded: lightshift energy
processing 2260/4390
✅ Embedded: lis technologies
processing 2280/4390
✅ Embedded: Logan Energy
processing 2300/4390
✅ Embedded: Lucid Motors
processing 2320/4390
✅ Embedded: m2i life sciences
processing 2340/4390
✅ Embedded: manex ai
processing 2360/4390
✅ Embedded: Mast Reforestation
processing 2380/4390
✅ Embedded: Maya Climate
processing 2400/4390
✅ Embedded: metafin
processing 2420/4390
✅ Embedded: Mighty Buildings
processing 2440/4390
✅ Embedded: Mito Material Solutions
processing 2460/4390
✅ Embedded: Modulous
processing 2480/4390
✅ Embedded: Mondra
processing 2500/4390
✅ Embedded: Mote
processing 2520/4390
✅ Embedded: MURAL
processing 2540/4390
✅ Embedded: Nala Earth
processing 2560/4390
✅ Embedded: navitas solar
processing 2580/4390
✅ Embedded: Neural Concept
processing 2600/4390
✅ Embedded: Next Generation Esports (NGE)
processing 2620/4390
✅ Embedded: nikola motors
processing 2640/4390
✅ Embedded: Nomad Solar Energy
processing 2660/4390
✅ Embedded: nosh
processing 2680/4390
✅ Embedded: novo holdings
processing 2700/4390
✅ Embedded: Nukoko
processing 2720/4390
✅ Embedded: Obeo Biogas
processing 2740/4390
✅ Embedded: Odd.Bot
processing 2760/4390
✅ Embedded: Omnidian
processing 2780/4390
✅ Embedded: OnSight Technology
processing 2800/4390
✅ Embedded: Opscura
processing 2820/4390
✅ Embedded: Orchard Robotics
processing 2840/4390
✅ Embedded: polymateria
processing 2860/4390
✅ Embedded: Pachama
processing 2880/4390
✅ Embedded: Parallel Carbon Limited
processing 2900/4390
✅ Embedded: pawco foods
processing 2920/4390
✅ Embedded: Perfeggt.
processing 2940/4390
✅ Embedded: Phoenix Tailings
processing 2960/4390
✅ Embedded: Pina Earth
processing 2980/4390
✅ Embedded: Planet FWD
processing 3000/4390
✅ Embedded: plenty
processing 3020/4390
✅ Embedded: porter road
processing 3040/4390
✅ Embedded: Raad Labs
processing 3060/4390
✅ Embedded: QAPTIS
processing 3080/4390
✅ Embedded: Provenance
processing 3100/4390
✅ Embedded: pure harvest smart farms
processing 3120/4390
✅ Embedded: Qnovo
processing 3140/4390
✅ Embedded: radiant
processing 3160/4390
✅ Embedded: Raptor Maps
processing 3180/4390
✅ Embedded: recover
processing 3200/4390
✅ Embedded: Refactor Capital
processing 3220/4390
✅ Embedded: RenewRisk
processing 3240/4390
✅ Embedded: reSeed Ventures
processing 3260/4390
✅ Embedded: Revent
processing 3280/4390
✅ Embedded: Ridepanda
processing 3300/4390
✅ Embedded: RMG Acquisition III
processing 3320/4390
✅ Embedded: RootWave
processing 3340/4390
✅ Embedded: Ryp Labs,
processing 3360/4390
✅ Embedded: sapphire technologies
processing 3380/4390
✅ Embedded: Scoot Science
processing 3400/4390
✅ Embedded: Seenons
processing 3420/4390
✅ Embedded: SensorFlow
processing 3440/4390
✅ Embedded: Sevan Multi-Site Solutions
processing 3460/4390
✅ Embedded: sightglass
processing 3480/4390
✅ Embedded: Single.Earth
processing 3500/4390
✅ Embedded: skydweller
processing 3520/4390
✅ Embedded: Smartcar
processing 3540/4390
✅ Embedded: Solar Foods
processing 3560/4390
✅ Embedded: SOLO
processing 3580/4390
✅ Embedded: sortera
processing 3600/4390
✅ Embedded: specifx data
processing 3620/4390
✅ Embedded: Spotta
processing 3640/4390
✅ Embedded: Starshot Capital
processing 3660/4390
✅ Embedded: Sustain.Life
processing 3680/4390
✅ Embedded: Subeca
processing 3700/4390
✅ Embedded: Sunhat
processing 3720/4390
✅ Embedded: superplum
processing 3740/4390
✅ Embedded: Swarm Engineering
processing 3760/4390
✅ Embedded: synaptec
processing 3780/4390
✅ Embedded: Tandem PV
processing 3800/4390
✅ Embedded: tembici.
processing 3820/4390
✅ Embedded: terra co2 technology
processing 3840/4390
✅ Embedded: the ancient environmental genomics initiative for sustainability
processing 3860/4390
✅ Embedded: the oman investment authority
processing 3880/4390
✅ Embedded: ThreeKit
processing 3900/4390
✅ Embedded: TOffeeAM
processing 3920/4390
✅ Embedded: track3d
processing 3940/4390
✅ Embedded: Trebellar
processing 3960/4390
✅ Embedded: Trucks Venture Capital
processing 3980/4390
✅ Embedded: tusimple
processing 4000/4390
✅ Embedded: ULEMCo
processing 4020/4390
✅ Embedded: Uniti - Electric Car
processing 4040/4390
✅ Embedded: UrbanChain
processing 4060/4390
✅ Embedded: Valar Atomics
processing 4080/4390
✅ Embedded: Veloce Energy Inc.
processing 4100/4390
✅ Embedded: Vericool Limited
processing 4120/4390
✅ Embedded: VFC
processing 4140/4390
✅ Embedded: Villanova University
processing 4160/4390
✅ Embedded: Vivid Machines
processing 4180/4390
✅ Embedded: Volta Trucks
processing 4200/4390
✅ Embedded: Vycarb
processing 4220/4390
✅ Embedded: WattBuy
processing 4240/4390
✅ Embedded: Wheelocity
processing 4260/4390
✅ Embedded: Wingcopter
processing 4280/4390
✅ Embedded: Wraithwatch
processing 4300/4390
✅ Embedded: Xiaomi
processing 4320/4390
✅ Embedded: Yeastup AG
processing 4340/4390
✅ Embedded: Zeedz
processing 4360/4390
✅ Embedded: Zero Motorcycles
processing 4380/4390
✅ Embedded: zoomo

In [86]:
query = "Solarcycle, Oakland, CA"
query_embedding = client.embeddings.create(
    model="text-embedding-3-small",
    input=query
).data[0].embedding

# Find a way to also process the querry into something that is more manageable
def search_companies_by_semantics(query_embedding, top_k=10):
    embedding_str = str(query_embedding)  # Converts list to PostgreSQL array syntax
    response = supabase.rpc(
        "match_companies_by_embedding",
        {"query_embedding": embedding_str, "match_count": top_k}
    ).execute()
    return response.data

for index, row in pd.DataFrame(search_companies_by_semantics(query_embedding)).iterrows():
    print(row.to_dict())
    break

{'name': 'SOLARCYCLE', 'tagline': 'Solar panel recycling company', 'domain': 'solarcycle.us', 'Location': 'Oakland, California'}

In [67]:
df[df["name"] =="tyba"]

Empty DataFrame
Columns: [id, name, tagline, domain, Location, Investors, Employees (Current), Employees: Growth YoY (%), Investment Stage, Last Funding Amount (USD), LinkedIn Profile (Founders/CEOs), In Energize Affinity, Affinity ID, Industry, Business Models, Technologies, embedding]
Index: []

In [14]:
import time
import imaplib
import email
from bs4 import BeautifulSoup
from uid_tracker import is_uid_seen, mark_uid_seen
from db_client import insert_deals, in_database, fetch_all_companies
from config import EMAIL_ADDRESS, EMAIL_PASSWORD, IMAP_SERVER, WATCHLIST
from website_monitor import get_new_ctvc, get_new_forutne
from parser import ctvc, fortune, cleaning
from affinity import enrich_df
import pandas as pd
from ctvc import get_new_ctvc
from fortune import get_new_forutne

In [4]:

# import datawrangler

new_ctvc = get_new_ctvc()
new_fortune = get_new_forutne()
new_newsletters = new_ctvc + new_fortune
ctvc_df = pd.DataFrame()
print(f"We have {len(new_ctvc)} CTVC newsletters")
c_count = 0
for new_url in new_ctvc:
    print(c_count)
    c_count+=1
    df = ctvc(new_url)
    if df is not None and not df.empty:
        print("concatenating ctvc")
        ctvc_df = pd.concat([ctvc_df,df])
    else:
        print("failed")
    # break

# print(ctvc_df)
print(f"We have {len(new_fortune)} fortune newsletters")

fortune_df = pd.DataFrame()
f_count = 0
for new_url in new_fortune:
    print(f_count)
    f_count+=1
    df = fortune(new_url)
    if df is not None and not df.empty:
        print("concatonating fortune")
        fortune_df = pd.concat([fortune_df,df])
    else:
        print("failed")
    # break
    # if not fortune_df.empty:
    #     break

print("combining ctvc and fortune")
all_data = pd.concat([ctvc_df,fortune_df])

We have 5 CTVC newsletters
0
concatenating ctvc
1
concatenating ctvc
2
concatenating ctvc
3
concatenating ctvc
4
concatenating ctvc
We have 14 fortune newsletters
0
concatonating fortune
1
concatonating fortune
2
concatonating fortune
3
concatonating fortune
4
Retrying classify_industry...
Retrying a second time
Couldn't extract
failed
5
concatonating fortune
6
Retrying classify_industry...
concatonating fortune
7
Retrying classify_industry...
Retrying a second time
Couldn't extract
failed
8
Retrying classify_industry...
Retrying a second time
Couldn't extract
failed
9
Classification error: invalid syntax (<unknown>, line 1)
Retrying classify_industry...
concatonating fortune
10
concatonating fortune
11
Retrying classify_industry...
Retrying a second time
Couldn't extract
failed
12
concatonating fortune
13
Retrying classify_industry...
Retrying a second time
Couldn't extract
failed
combining ctvc and fortune

In [9]:
all_data.sort_values(by="name")

,name,deal_size,series,tagline,location,investors,domain,date,source
9,AMEA Power,$72M,Project Finance Debt,Renewable energy developer,"Dubai, United Arab Emirates",International Finance Corporation (IFC),https://ameapower.com/,2025-06-23,https://www.ctvc.co/epa-puts-corn-on-the-polic...
28,Abundia Global Impact Group,,,Waste into renewable fuels conversion service ...,"New York City, NY",,,2025-07-07,https://www.ctvc.co/bright-spots-and-sunsets-i...
5,Aedifion,$20M,Series B,Building energy optimization software developer,"Köln, Germany","Eurazeo, World Fund, BitStone Capital, Drees &...",https://www.aedifion.com/,2025-06-30,https://www.ctvc.co/overheard-at-lcaw-252/
23,Agrobiomics,$9M,Grant,Biostimulants for crop health developer,"Copenhagen, Denmark",European Innovation Council,https://www.agrobiomics.com/,2025-07-07,https://www.ctvc.co/bright-spots-and-sunsets-i...
1,Amogy,$23M,Growth,Clean fuel technology provider,"Brooklyn, NY","KDB Silicon Valley, Korea Development Bank, Bo...",https://www.amogy.co/,2025-07-21,https://www.ctvc.co/grwm-for-nycw-255/
...,...,...,...,...,...,...,...,...,...
0,Xelix,$160M,Series B,Developer of AI software in accounts payable,"New York City, NY","Insight Partners, Passion Capital, LocalGlobe",https://www.xelix.com/,2025-07-22,https://fortune.com/2025/07/22/jeff-dean-googl...
15,Zemetric,Undisclosed,,Transport electrification technology provider,"Silicon Valley, CA",,https://zemetric.com/,2025-07-21,https://www.ctvc.co/grwm-for-nycw-255/
6,captoplastic,$2M,Series A,Microplastics capture technology developer,"Vicálvaro, Spain",BeAble Capital,https://captoplastic.com/,2025-06-23,https://www.ctvc.co/epa-puts-corn-on-the-polic...
16,eMotion Fleet,$2M,Series A,Fleet electrification services provider,"Shinjuku-ku, Japan","Incubate Fund, Kyushu Open Innovation Fund No....",https://www.emotionfleet.com/,2025-07-07,https://www.ctvc.co/bright-spots-and-sunsets-i...
13,pHydrogen,$2M,Seed,Green hydrogen developer,"Tokyo, Japan",Incubate Fund,https://www.phydrogen.com/,2025-06-30,https://www.ctvc.co/overheard-at-lcaw-252/

In [12]:
from parser import cleaning
print("cleaning")
companies, deals = cleaning(all_data)
print(f"final size of companies {companies.shape}")

companies

cleaning
Processing 1/112 rows...
Processing 21/112 rows...
Processing 41/112 rows...
Processing 61/112 rows...
Processing 81/112 rows...
Processing 101/112 rows...
final size of companies (112, 6)

,company,domain,location,tagline,investors,name
company_uuid,,,,,,
208e2efb-5bdc-4b27-9499-23ea0c55a61f,NaN,,"New York City, NY",Waste into renewable fuels conversion service ...,[],abundia global impact group
8a45bb4f-8ace-424a-bf8d-e28cad5bbc2f,NaN,https://www.aedifion.com/,"Köln, Germany",Building energy optimization software developer,"[eurazeo, hopp family office, world fund, dree...",aedifion
71eefbf9-c523-43e6-9b8d-bf3f6f746e50,NaN,https://www.agrobiomics.com/,"Copenhagen, Denmark",Biostimulants for crop health developer,[european innovation council],agrobiomics
ab168960-3869-457b-9ca3-b401fab975dc,NaN,https://ameapower.com/,"Dubai, United Arab Emirates",Renewable energy developer,[international finance corporation (ifc)],amea power
9032041b-bc9f-4115-8687-47aeb8c516e8,NaN,https://www.amogy.co/,"Brooklyn, NY",Clean fuel technology provider,"[jb investment, kdb silicon valley, bonangels ...",amogy
...,...,...,...,...,...,...
54f35751-0667-46ce-a671-87327edeeb63,NaN,https://www.vokbikes.com/,"Tallinn, Estonia",Heavy-duty electric cargo bike manufacturer,"[sunly, smartcap, specialist vc, sqm lithium v...",vok bikes
e4dd3999-8ee9-45e9-b7cc-77a0b5876097,NaN,https://www.woodchuck.com/,"Grand Rapids, MI",Streamlines wood waste and biomass processing ...,"[northstar clean energy, alloy partners, becke...",woodchuck
93f5c892-af1b-4941-8395-dd7bc3cdb6cd,NaN,https://xatoms.com/,"Toronto, Canada",AI-driven water purification materials developer,"[bdc capital, quantacet, boxone ventures, gene...",xatoms
e536f7fd-a936-4378-9cb0-eb4d4d6604d8,NaN,https://www.xelix.com/,"New York City, NY",Developer of AI software in accounts payable,"[passion capital, insight partners, localglobe]",xelix
60843963-2373-458a-9e26-168e1b2ff009,NaN,https://zemetric.com/,"Silicon Valley, CA",Transport electrification technology provider,[],zemetric

In [13]:
from db_client import fetch_all

deals = pd.DataFrame(fetch_all(table="funding"))

In [19]:

def deal_in_database(row,deals,date_tolerance_days = 60):
    company_uuid = row["company_uuid"]
    if company_uuid in  deals["company_uuid"].values:
        date = datetime.strptime(row["date"],"%Y-%m-%d")
        matching_deals = deals[deals["company_uuid"] == company_uuid]
        matching_deals["date"] = pd.to_datetime(matching_deals["date"])
        for index, deal in matching_deals.iterrows():
            date_match = False
            if pd.notna(date) and pd.notna(deal["date"]):
                date_match = abs((date - deal["date"]).days)
                if date_match <= date_tolerance_days:
                    return True
    return False

row = {"company_uuid":"4ec18937-c30b-4034-9721-6c89bcef58cb","date":"2023-11-13"}

deal_in_database(row,deals)

True

In [9]:
from datetime import datetime
datetime.strptime("2022-03-14", "%Y-%m-%d")

datetime.datetime(2022, 3, 14, 0, 0)

In [ ]:
for index, row in enriched_companies.iterrows():
    from_db = in_database(row,db)
    if from_db is not False:
        existing_id = from_db["id"]
        temp_id = row["id"]
        to_change = deals[deals["company_id"] == temp_id]
        for i, deal in to_change.iterrows():
            deals.at[i,"company_id"] = existing_id
            # deals.at[]
    else:
        pass    # add row to database

In [3]:



import time
import imaplib
import email
from bs4 import BeautifulSoup
from uid_tracker import is_uid_seen, mark_uid_seen
from db_client import company_in_database, fetch_all, unseen_deals, upload_dataframe
from config import EMAIL_ADDRESS, EMAIL_PASSWORD, IMAP_SERVER, WATCHLIST
from parser import ctvc, fortune, cleaning
from affinity import enrich_df, affinity_enrich
import pandas as pd
from ctvc import get_new_ctvc
from fortune import get_new_forutne
import warnings
from embeddings import embed_companies
warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", message="Unverified HTTPS request")

new_ctvc = get_new_ctvc()
new_fortune = get_new_forutne()
new_newsletters = new_ctvc + new_fortune
ctvc_df = pd.DataFrame()
print(f"We have {len(new_ctvc)} CTVC newsletters")
c_count = 0
for new_url in new_ctvc:
    print(c_count)
    c_count+=1
    df = ctvc(new_url)
    if df is not None and not df.empty:
        print("concatenating ctvc")
        ctvc_df = pd.concat([ctvc_df,df])
    else:
        print("failed")

print(f"We have {len(new_fortune)} fortune newsletters")

We have 5 CTVC newsletters
0
concatenating ctvc
1
concatenating ctvc
2
concatenating ctvc
3
concatenating ctvc
4
concatenating ctvc
We have 14 fortune newsletters

In [25]:

fortune_df = pd.DataFrame()
f_count = 0
for new_url in new_fortune:
    print(f_count)
    f_count+=1
    df = fortune(new_url)
    if df is not None and not df.empty:
        print("concatonating fortune")
        fortune_df = pd.concat([fortune_df,df])
    else:
        print("failed")
    break

print("combining ctvc and fortune")
all_data = pd.concat([ctvc_df,fortune_df])
companies, deals = cleaning(all_data)

0
concatonating fortune
combining ctvc and fortune
Processing 1/94 rows...
Processing 21/94 rows...
Processing 41/94 rows...
Processing 61/94 rows...
Processing 81/94 rows...

In [43]:
companies

,name,domain,location,tagline,investors
company_uuid,,,,,
ef66c221-2bf8-41e0-803c-1ba19f63b306,abundia global impact group,,"New York City, NY",Waste into renewable fuels conversion service ...,[houston american energy corp]
9b5963f9-3c27-41f9-b593-b481710d5dd4,aedifion,https://www.aedifion.com/,"Köln, Germany",Building energy optimization software developer,"[drees & sommer, hopp family office, world fun..."
543a0e42-a3aa-49fe-9da2-d5c162b166be,agrobiomics,https://agrobiomics.com/,"Copenhagen, Denmark",Biostimulants for crop health developer,[european innovation council]
3c299c69-bdbd-4a64-be3d-6acd1c7d6348,amea power,https://www.ameapower.com/,"Dubai, United Arab Emirates",Renewable energy developer,[international finance corporation (ifc)]
3c21ce93-9ec1-4375-b32c-cf455a598e20,amogy,https://www.amogy.co/,"Brooklyn, NY",Clean fuel technology provider,"[jb investment, bonangels venture partners, ko..."
...,...,...,...,...,...
c705bf1b-bd87-4613-93e4-d3529f1bba1a,tulum energy,https://tulumenergy.com/,"Luxembourg, Luxembourg",Clean hydrogen producer,"[mito technology (mito tech ventures), tdk ven..."
0b4ef153-728f-42a2-a048-39c98dd8cad7,ukrhydroenergo,,"Vyshgorodskiy Rayon, Ukraine",Hydropower generator,[european investment bank (eib)]
c9437a50-0958-4156-a694-8b4710760342,vok bikes,https://vokbikes.com/,"Tallinn, Estonia",Heavy-duty electric cargo bike manufacturer,"[sunly, metaplanet holdings, smartcap, special..."
e40b9200-5ed7-4690-9353-a93f4edfbe57,woodchuck,https://woodchuck.com/,"Grand Rapids, MI",Streamlines wood waste and biomass processing ...,"[northstar clean energy, alloy partners, becke..."
81b4972c-1ee1-4e88-80f3-60e0eb49419b,xatoms,https://www.xatoms.com/,"Toronto, Canada",AI-driven water purification materials developer,"[quantacet, genesis ventures, boxone ventures,..."

In [6]:
from affinity import affinity_enrich
result = []
count = 0
for index, row in companies.iterrows():
    print(row["name"], count)
    result.append(affinity_enrich(row))
    count+=1
companies = pd.DataFrame(result)

abundia global impact group 0
aedifion 1
agrobiomics 2
amea power 3
amogy 4
antler bio 5
assetcool 6
atome 7
biomedit 8
blueredgold 9
busup 10
captoplastic 11
carbyon 12
cariqa 13
catalyxx 14
cellugy 15
chloris geospatial 16
clearway energy group 17
climate tech partners 18
climatiq 19
climeworks 20
coco robotics 21
colorifix 22
cosma 23
creative energy 24
crosstown h2r 25
currentt 26
dexter energy 27
doktar technologies 28
echandia 29
eeki foods 30
elemental advanced materials 31
emerald ai 32
emotion fleet 33
enter 34
eos energy enterprises 35
equitable earth 36
ess 37
evera cabs 38
fiber elements 39
fieldfactors 40
freight farms 41
ftc solar 42
geologicai 43
gridserve 44
halter 45
helical fusion 46
hived 47
hymeth 48
ignis h2 energy 49
insight m 50
intelligent energy 51
inyanga marine energy group 52
jälle technologies 53
lbc tank terminals 54
libre foods 55
light bridge 56
lightshift energy 57
loopworm 58
lumenstream 59
mars 60
membrion 61
minesto 62
momenta 63
move mobility 64
mufin green finance 65
nevoya 66
novoloop 67
octopus energy generation 68
oklo 69
pano 70
parspec 71
phydrogen 72
polestar 73
provectus algae 74
puna bio 75
recurrent energy 76
reset company 77
rise robotics 78
rival foods 79
rivian 80
saltx technology 81
sds separation 82
seaturns 83
sparc hydrogen 84
steady energy 85
tarnoc 86
terra co2 technology 87
terrapower 88
tibo energy 89
tulum energy 90
ukrhydroenergo 91
vok bikes 92
woodchuck 93
xatoms 94

In [44]:
companies

,name,domain,location,tagline,investors
company_uuid,,,,,
ef66c221-2bf8-41e0-803c-1ba19f63b306,abundia global impact group,,"New York City, NY",Waste into renewable fuels conversion service ...,[houston american energy corp]
9b5963f9-3c27-41f9-b593-b481710d5dd4,aedifion,https://www.aedifion.com/,"Köln, Germany",Building energy optimization software developer,"[drees & sommer, hopp family office, world fun..."
543a0e42-a3aa-49fe-9da2-d5c162b166be,agrobiomics,https://agrobiomics.com/,"Copenhagen, Denmark",Biostimulants for crop health developer,[european innovation council]
3c299c69-bdbd-4a64-be3d-6acd1c7d6348,amea power,https://www.ameapower.com/,"Dubai, United Arab Emirates",Renewable energy developer,[international finance corporation (ifc)]
3c21ce93-9ec1-4375-b32c-cf455a598e20,amogy,https://www.amogy.co/,"Brooklyn, NY",Clean fuel technology provider,"[jb investment, bonangels venture partners, ko..."
...,...,...,...,...,...
c705bf1b-bd87-4613-93e4-d3529f1bba1a,tulum energy,https://tulumenergy.com/,"Luxembourg, Luxembourg",Clean hydrogen producer,"[mito technology (mito tech ventures), tdk ven..."
0b4ef153-728f-42a2-a048-39c98dd8cad7,ukrhydroenergo,,"Vyshgorodskiy Rayon, Ukraine",Hydropower generator,[european investment bank (eib)]
c9437a50-0958-4156-a694-8b4710760342,vok bikes,https://vokbikes.com/,"Tallinn, Estonia",Heavy-duty electric cargo bike manufacturer,"[sunly, metaplanet holdings, smartcap, special..."
e40b9200-5ed7-4690-9353-a93f4edfbe57,woodchuck,https://woodchuck.com/,"Grand Rapids, MI",Streamlines wood waste and biomass processing ...,"[northstar clean energy, alloy partners, becke..."
81b4972c-1ee1-4e88-80f3-60e0eb49419b,xatoms,https://www.xatoms.com/,"Toronto, Canada",AI-driven water purification materials developer,"[quantacet, genesis ventures, boxone ventures,..."

In [8]:
print(f" We have this many companies {companies.shape[0]}")
print(f" We have this many deals {deals.shape[0]}")

 We have this many companies 95
 We have this many deals 95

In [36]:
db = pd.DataFrame(fetch_all("companies"))
print("fetched all companies")

fetched all companies

In [37]:
db.columns

Index(['company_uuid', 'name', 'tagline', 'domain', 'location', 'investors',
       'Employees (Current)', 'Employees: Growth YoY (%)', 'Investment Stage',
       'Last Funding Amount (USD)', 'LinkedIn Profile (Founders/CEOs)',
       'In Energize Affinity', 'Affinity ID', 'Industry', 'Business Models',
       'Technologies', 'embedding'],
      dtype='object')

In [38]:
print(deals["company_uuid"].apply(type).value_counts())

company_uuid
<class 'str'>    94
Name: count, dtype: int64

In [40]:
import importlib, db_client
importlib.reload(db_client)

from db_client import (
    company_in_database,
    fetch_all,
    unseen_deals,
    upload_dataframe,
)


to_keep = pd.DataFrame()
count = 94
for index, row in companies.iterrows():
    print(f"We have {count} left")
    print(f"checking if --{row["name"].upper()}-- is in database")
    from_db = company_in_database(row,db)
    if from_db is not None:
        print(from_db.to_dict().keys())
        print(f"--{row["name"].upper()}-- is INDEED in the database")
        # print(f"from_db is type: {type(from_db)} and its value is {from_db} ")
        existing_id = from_db["company_uuid"]
        print("The existing id is", type(existing_id))
        print("The value of the existing is",existing_id)
        existing_name = from_db["name"]
        temp_id = row["company_uuid"]
        print("this is the temp_id :",temp_id, "And it is of type", type(temp_id))
        to_change = deals[deals["company_uuid"] == temp_id]
        for i, deal in to_change.iterrows():
            print(f"changed id from {temp_id} to {existing_id}")
            deals.at[i,"company_uuid"] = existing_id
            deals.at[i,"name"] = existing_name
    else:
        print(f"{row["name"]} is NOT in the database")
        to_keep = pd.concat([to_keep,row.to_frame().T])
    count-=1

deals = unseen_deals(deals)
companies = to_keep.apply(embed_companies,axis=1)

print(f"After checking the database we have {companies.shape[0]} new companies")

We have 94 left
checking if --ABUNDIA GLOBAL IMPACT GROUP-- is in database
abundia global impact group is NOT in the database
We have 93 left
checking if --AEDIFION-- is in database
aedifion is NOT in the database
We have 92 left
checking if --AGROBIOMICS-- is in database
agrobiomics is NOT in the database
We have 91 left
checking if --AMEA POWER-- is in database
amea power is NOT in the database
We have 90 left
checking if --AMOGY-- is in database
amogy is NOT in the database
We have 89 left
checking if --ANTLER BIO-- is in database
antler bio is NOT in the database
We have 88 left
checking if --ASSETCOOL-- is in database
assetcool is NOT in the database
We have 87 left
checking if --ATOME-- is in database
atome is NOT in the database
We have 86 left
checking if --BIOMEDIT-- is in database
biomedit is NOT in the database
We have 85 left
checking if --BLUEREDGOLD-- is in database
blueredgold is NOT in the database
We have 84 left
checking if --BUSUP-- is in database
busup is NOT in the database
We have 83 left
checking if --CAPTOPLASTIC-- is in database

KeyboardInterrupt:

In [ ]:
deals

In [ ]:
companies

In [ ]:
upload_dataframe(companies,"companies")
upload_dataframe(deals,"funding")

In [1]:
from parser_new_cleaned import keepcool

df = keepcool("https://www.keepcool.co/p/summer-break")

this is the url

In [2]:
df

,name,deal_size,series,tagline,location,investors,domain,date,source
0,RideAlso,$200M,,Small EVs designed for city use and ride-hailing,"Palo Alto, California",Greenoaks Capital,https://ridealso.com/,2025-07-22,https://www.keepcool.co/p/summer-break
1,Climeworks,$162M,,Direct Air Capture technology,"Zurich, Switzerland","BigPoint Holding, Partners Group",https://www.climeworks.com/,2025-07-22,https://www.keepcool.co/p/summer-break
2,Gridserve,$135M,,EV charging stations and solar-powered service...,"Buckinghamshire, U.K.","TPG, Infracapital, Mitsubishi",https://gridserve.com/,2025-07-22,https://www.keepcool.co/p/summer-break
3,Exodigo,$96M,Series B,AI-powered underground infrastructure mapping ...,"Palo Alto, California","Zeev Ventures, Greenfield Partners",https://www.exodigo.com/,2025-07-22,https://www.keepcool.co/p/summer-break
4,Bedrock Robotics,$80M,,Autonomous construction equipment,"San Francisco, California","Eclipse, 8VC",https://bedrockrobotics.com/,2025-07-22,https://www.keepcool.co/p/summer-break
5,Amogy,$80M,,Ammonia-to-power technology for shipping and d...,"Brooklyn, New York","Korea Development Bank, KDB Silicon Valley LLC",https://amogy.co/,2025-07-22,https://www.keepcool.co/p/summer-break
6,Q.ant,$72.5M,Series A,Photonics processors for AI and high-performan...,"Stuttgart, Germany","Cherry Ventures, UVC Partners, imec.xpand",https://qant.com/,2025-07-22,https://www.keepcool.co/p/summer-break
7,Nitricity,$63M,,Organic fertilizer plant using renewable energy,California,"Energy Impact Partners, Khosla Ventures",https://nitricity.co/,2025-07-22,https://www.keepcool.co/p/summer-break
8,BrightAI,$51M,Series A,AI-powered industrial power system management ...,"San Francisco, California","Khosla Ventures, Inspired Capital",https://bright.ai/,2025-07-22,https://www.keepcool.co/p/summer-break
9,GeologicAI,$44M,Series B,Automated rock core analysis for mining companies,"Calgary, Canada","Blue Earth Capital, Rio Tinto, BHP Ventures",https://geologicai.com/,2025-07-22,https://www.keepcool.co/p/summer-break
10,HIVED,$42M,Series B,All-electric delivery service,London,"Nordic Ninja, Elemental Impact",https://hived.space/,2025-07-22,https://www.keepcool.co/p/summer-break
11,Donut Lab,$29.25M,seed,Modular EV platform and five-motor lineup,Finland,Risto Siilasmaa,https://donutlab.com/,2025-07-22,https://www.keepcool.co/p/summer-break
12,Dexter Energy,$26.9M,Series C,AI-driven energy forecasting platform,"Amsterdam, Netherlands",Klima Capital,https://dexterenergy.ai/,2025-07-22,https://www.keepcool.co/p/summer-break
13,Stellaria,$26.9M,seed,Molten salt nuclear reactors,"Grenoble, France","One Ventures, Supernova Invest",https://stellaria.fr/,2025-07-22,https://www.keepcool.co/p/summer-break
14,Tulum Energy,$26.8M,seed,'Turquoise' hydrogen via methane pyrolysis,"Milan, Italy","TDK Ventures, CDP Venture Capital",https://tulum.energy/,2025-07-22,https://www.keepcool.co/p/summer-break
15,Arago,$25.9M,seed,Energy-efficient photonic AI chips,"Paris, France","Earlybird, Protagonist, Visionaries Tomorrow",https://arago.inc/,2025-07-22,https://www.keepcool.co/p/summer-break
16,EmeraldAI,$24.5M,seed,AI data centers with computational flexibility,"San Jose, CA",Radical Ventures,https://emeraldai.co/,2025-07-22,https://www.keepcool.co/p/summer-break
17,Motor AI,$20M,seed,Neuroscience-informed autonomous driving techn...,Berlin,,https://motor-ai.com/,2025-07-22,https://www.keepcool.co/p/summer-break
18,Helical Fusion,$15M,Series A,Stellarator fusion reactor design,"Tokyo, Japan","SBI Investment, Keio Innovation Initiative",https://helicalfusion.com/,2025-07-22,https://www.keepcool.co/p/summer-break
19,AssetCool,$13.5M,Series A,Advanced coatings for power lines,"Leeds, England","Energy Impact Partners, Extantia",https://assetcool.com/,2025-07-22,https://www.keepcool.co/p/summer-break
20,Unblock,$13.5M,,Data centers converting wasted energy into com...,"Buenos Aires, Argentina","Goldcrest Capital, Collaborative Fund",https://unblock.energy/,2025-07-22,https://www.keepcool.co/p/summer-break
21,FlyGuys,$13M,Series A-1,Drone-based aerial data collection services,"Lafayette, Louisiana",Wonder Fund North Dakota,https://flyguys.com/,2025-07-22,https://www.keepcool.co/p/summer-break
22,Membrion,$11.3M,Series C,Ceramic desalination membranes,"Seattle, Washington",,https://membrion.com/,2025-07-22,https://www.keepcool.co/p/summer-break
23,Chloris Geospatial,$8.5M,Series A,Natural capital carbon monitoring solutions,"Newton, Massachusetts","Future Energy Ventures, AXA Investment Managers",https://chloris.earth/,2025-07-22,https://www.keepcool.co/p/summer-break
24,Tibo Energy,$7 million,seed,Energy management platform,"Eindhoven, Netherlands","KOMPAS, Hitachi Ventures",https://tibo.energy/,2025-07-22,https://www.keepcool.co/p/summer-break
25,Alva Energie,$6.1 million,,Decentralized energy management solutions,"Berlin, Germany","Triodos Bank, Württembergische Energie",https://alva-energie.de/,2025-07-22,https://www.keepcool.co/p/summer-break
26,Vok Bikes,$5.85 million,Series A,Heavy-duty electric cargo bikes,"Tallinn, Estonia","SQM Lithium Ventures, Metaplanet Holdings",https://vokbikes.com/,2025-07-22,https://www.keepcool.co/p/summer-break
27,Inyanga Marine Energy Group,$5 million,growth,Offshore renewable energy project services,"Falmouth, England","British Business Bank, The FSE Group",https://inyangamarine.com/,2025-07-22,https://www.keepcool.co/p/summer-break
28,Cariqa,$4.7 million,seed,EV charging payment and network management sof...,"Berlin, Germany","Anthemis Group, Contrarian Ventures",https://cariqa.com/,2025-07-22,https://www.keepcool.co/p/summer-break
29,Wood Chuck,$3.75 million,seed,Wood waste and biomass processing services,"Grand Rapids, Michigan","Alloy Partners, Beckett Industries",https://woodchuck.ai/,2025-07-22,https://www.keepcool.co/p/summer-break
30,Loopworm,$3.25 million,seed,Insects for animal feed and cosmetic inputs,"Bangalore, India","Enrission India Capital, WaterBridge Ventures",https://loopworm.in/,2025-07-22,https://www.keepcool.co/p/summer-break
31,CrosstownH2R,$3 million,seed,Gas turbine decarbonization technology,"Zurich, Switzerland","2100 Ventures, Climate Insiders",https://crosstown-h2r.com/,2025-07-22,https://www.keepcool.co/p/summer-break
32,Fiber Elements,$3 million,seed,Bio-based fiber and polymer composite manufact...,"Leoben, Austria","Amadeus Capital Partners, LEA Partners",https://fiber-elements.com/,2025-07-22,https://www.keepcool.co/p/summer-break
33,Cosma,$2.9 million,seed,Autonomous benthic monitoring technology,"Nice, France","Ternel, Wind Capital",https://cosma.tech/,2025-07-22,https://www.keepcool.co/p/summer-break
34,RarEarth,$3 million,,Rare elements recycling and magnet production,Italy,Primo Capital,https://rarearth.it/,2025-07-22,https://www.keepcool.co/p/summer-break
35,YPlasma,$2.5 million,seed,Ultra-efficient plasma actuators,Spain,Faber VC,https://yplasma.tech/,2025-07-22,https://www.keepcool.co/p/summer-break
36,Jälle Technologies,$2 million,pre-seed,Lithium-ion battery recycling and graphite was...,"Tallinn, Estonia","Enterprise Estonia, Environmental Investment C...",https://jalletech.com/,2025-07-22,https://www.keepcool.co/p/summer-break
37,Tarnoc,$1.4 million,seed,Electric turbine heat pumps,"Delft, Netherlands",,https://tarnoc.nl/,2025-07-22,https://www.keepcool.co/p/summer-break
38,Steady Energy,$37.4 million,,Small modular nuclear reactors,"Espoo, Finland","92 Ventures, Local Tapiola",https://steadyenergy.com/,2025-07-22,https://www.keepcool.co/p/summer-break
39,Puna Bio,,Series A,Extremophile-based seed treatments,"Buenos Aires, Argentina","Gates Foundation, Corteva Catalyst, At One Ven...",https://puna.bio/,2025-07-22,https://www.keepcool.co/p/summer-break
40,Amperon,,,AI-powered energy forecasting platform,"Houston, Texas",Acario,https://amperon.co/,2025-07-22,https://www.keepcool.co/p/summer-break